### ISSUE TITLE
Project Goals

### ISSUE THREAD

**Issue by arjunmenon** [sparkbox/bouncy-ball#7]
Hey a suggestion.
In addition to three very useful project goals, please consider adding one more - Performance.

Each of the techniques does things in its own manner for different use cases. Some are good for certain things. So a suggestion, not asking universal but of yours, of which would give the best performance would be helpful as well.

**Comment by bryanbraun** [comment]
@arjunmenon, web animation performance is a big and important topic, but it's not as simple as saying which one is best. As you mentioned, each technique has it's own use-cases and performance is highly situational. Any type of comparison or ranking we could come up with is going to be imperfect.

That being said, I agree that there's more we could do around performance. Instead of making performance profiling a major goal of this project, I'm more comfortable with fitting performance under the goal to educate.

Practically speaking, this means I'd rather provide resources and guidance to help developers evaluate performance for themselves, instead of building interactive rankings and comparisons with our animations.

Do you know of any good resources for animation performance. We can start by putting together a section in the README and go from there.

**Comment by bryanbraun** [comment]
@arjunmenon, I've started a list of performance resources in the README. You might be interested in one I listed... [GreenSock's interactive performance comparison of several animation techniques](https://greensock.com/js/speed.html).

Let me know if you have any other suggestions. 👍
